GET http://localhost:3001/todos
###
POST http://localhost:3001/todo/new 
Content-Type: application/json

{
"text": "Order momos"
}
###

DELETE http://localhost:3001/todo/delete/64b265091dc9ba627e65774f

###

PUT  http://localhost:3001/todo/complete/64b264991dc9ba627e65774a

###

